# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tictactoe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftictactoe.proto\"5\n\x0fGreetingMessage\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"J\n\x10GreetingResponse\x12\x14\n\x0cresponder_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"9\n\x0f\x45lectionMessage\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x65lection_id\x18\x02 \x01(\x05\"4\n\x0e\x45lectionResult\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32x\n\tTicTacToe\x12\x35\n\x0cSendGreeting\x12\x10.GreetingMessage\x1a\x11.GreetingResponse\"\x00\x12\x34\n\rStartElection\x12\x10.ElectionMessage\x1a\x0f.ElectionResult\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tictactoe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GREETINGMESSAGE._serialized_start=19
  _GREETINGMESSAGE._serialized_end=72
  _GREETINGRESPONSE._serialized_start=74
  _GREETINGRESPONSE._serialized_end=148
  _ELECTIONMESSAGE._serialized_start=150
  _ELECTIONMESSAGE._serialized_end=207
  _ELECTIONRESULT._serialized_start=209
  _ELECTIONRESULT._serialized_end=261
  _TICTACTOE._serialized_start=263
  _TICTACTOE._serialized_end=383
# @@protoc_insertion_point(module_scope)
